# Generated by Django 4.2.7 on 2023-11-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "cuisine_name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("method", models.CharField(max_length=30)),
                ("category", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "ingredient_name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=30)),
                ("calories", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "recipe_id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cook_time", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                ("process", models.TextField()),
                (
                    "cuisine_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.cuisine"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refrigerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "review_id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField()),
                (
                    "recipe_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.recipe"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refrigerator_Stores_Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ingredient"
                    ),
                ),
                (
                    "refrigerator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.refrigerator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="refrigerator",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
        migrations.CreateModel(
            name="Recipe_Needs_Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ingredient"
                    ),
                ),
                (
                    "recipe_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.recipe"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="refrigerator_stores_ingredient",
            constraint=models.UniqueConstraint(
                fields=("refrigerator", "ingredient_name"),
                name="unique_refrigerator_ingredient",
            ),
        ),
        migrations.AddConstraint(
            model_name="refrigerator",
            constraint=models.UniqueConstraint(
                fields=("user_id", "created_at"), name="unique_refrigerator"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe_needs_ingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe_id", "ingredient_name"), name="unique_recipe_ingredient"
            ),
        ),
    ]
